import { computeBuildStats, type BuildConfig } from "../src/data/gameStats";
import { updateAbilityDefinitions } from "../src/data/eocAbilities";
import { updateUniqueDefinitions } from "../src/data/eocUniques";
import { updateBaseEquipmentDefinitions } from "../src/data/eocBaseEquipment";
import { updateModifierDefinitions } from "../src/data/eocModifiers";
import { parseEquipmentCSV, parseEquipmentModifiersCSV } from "../src/lib/parseSheetData";
import abilitiesJson from "../src/data/eocAbilities.generated.json";
import uniquesJson from "../src/data/eocUniques.generated.json";
import { readFileSync } from "node:fs";
import { join } from "node:path";

updateAbilityDefinitions(abilitiesJson as any);
updateUniqueDefinitions(uniquesJson as any);

// Load crafted base equipment + modifier defs from the CSV sources-of-truth.
const root = join(__dirname, "..");
updateBaseEquipmentDefinitions(parseEquipmentCSV(readFileSync(join(root, "equipment(1.3.2).csv"), "utf-8")));
updateModifierDefinitions(
  parseEquipmentModifiersCSV(readFileSync(join(root, "equipment_modifiers(1.3.2).csv"), "utf-8"))
);

const config: BuildConfig = {
  upgradeLevels: {
    "sorcerer/increasedEnergyShield": 5,
    "sorcerer/increasedSpellDamage": 5,
    "arcanist/increasedEnergyShield": 5,
    "arcanist/increasedSpellCriticalHitChance": 5,
    "arcanist/increasedManaRegeneration": 5,
    "druid/increasedChanceToInflictElementalAilments": 5,
    "druid/increasedMana": 5,
    "druid/increasedEnergyShield": 5,
    "archmage/increasedEnergyShield": 5,
    "archmage/increasedSpellDamage": 5,
    "archmage/increasedCastSpeed": 5,
    "archmage/increasedIntelligence": 5,
    "archmage/increasedMana": 5,
    "guardian/increasedArmourAndEnergyShield": 5,
    "guardian/increasedMana": 5,
    "guardian/increasedChaosResistance": 5,
    "zealot/increasedArmourAndEnergyShield": 5,
    "trickster/increasedEvasionRatingAndEnergyShield": 5,
    "trickster/increasedAttackSpeedAndCastSpeed": 5,
    "trickster/increasedChanceToDodge": 5,
  },
  equipmentModifiers: {
    flatLife: 0,
    flatMana: 457,
    flatArmour: 138,
    flatEvasion: 215,
    flatDamageMin: 0,
    flatDamageMax: 0,
    flatFireMin: 0,
    flatFireMax: 0,
    flatColdMin: 0,
    flatColdMax: 0,
    flatLightningMin: 0,
    flatLightningMax: 0,
    flatChaosMin: 0,
    flatChaosMax: 0,
    flatSpellDamageMin: 0,
    flatSpellDamageMax: 0,
    flatSpellFireMin: 0,
    flatSpellFireMax: 0,
    flatSpellColdMin: 67,
    flatSpellColdMax: 257,
    flatSpellLightningMin: 0,
    flatSpellLightningMax: 0,
    flatSpellChaosMin: 0,
    flatSpellChaosMax: 0,
    critChanceBonus: 0,
    strBonus: 100,
    dexBonus: 100,
    intBonus: 322,
    flatAccuracy: 0,
    armourPer10IntFromGear: 0,
    avoidAilmentsChanceFromGear: 0,
    avoidElementalAilmentsChanceFromGear: 0,
    enemyLoseMaxLifeAtStartPercentFromGear: 0,
    executeEnemiesBelowLifePercentFromGear: 0,
    executeEnemiesBelowLifePercentEqualToChillEffectFromGear: false,
    periodicShockPctFromGear: 0,
    periodicShockEverySecFromGear: 0,
    periodicLifeRegenPctFromGear: 0,
    periodicLifeRegenEverySecFromGear: 0,
    periodicLifeRegenDurationSecFromGear: 0,
    armourNoEffectVsPhysicalFromGear: false,
    chaosDamageCanIgniteFromGear: false,
    lightningDamageCanPoisonFromGear: false,
    chaosDamageCanInflictAllElementalAilmentsFromGear: false,
    allElementalDamageTypesCanChillFromGear: false,
    allElementalDamageTypesCanIgniteFromGear: false,
    allElementalDamageTypesCanShockFromGear: false,
    critsAlwaysInflictPoisonFromGear: false,
    critsAlwaysInflictElementalAilmentsFromGear: false,
    ignoreMaxShockEffectFromGear: false,
    fixedShockEffectPercentFromGear: 0,
    randomIgniteDurationLessPercentFromGear: 0,
    randomIgniteDurationMorePercentFromGear: 0,
    chillYouInflictInfiniteDurationFromGear: false,
    takePhysicalDamagePercentOfMaxLifeWhenYouAttackFromGear: 0,
    ailmentsOnCritGainDurationPerCritMultiFromGear: false,
    actionBarSetToPercentAfterCastFromGear: 0,
    actionBarFilledByPercentOnBlockFromGear: 0,
    firstAttackAlwaysCritFromGear: false,
    actionBarSetToPercentAtStartFromGear: 0,
    additionalBaseManaCostPctOfMaxEnergyShieldFromGear: 0,
    weaponLocalDamageAppliesToSpellsFromGear: false,
    meleeCritChanceIncPctPer10IntFromGear: 0,
    flatLifePerMagicItemEquippedFromGear: 0,
    hitsInflictChillAsThoughDealingMoreDamagePctFromGear: 0,
    leechAppliesToBleedDotFromGear: false,
    classPassivesEffectIncreasedPercentFromGear: 0,
    classPassivesEffectConditionMetFromGear: false,
    pctIncreasedExperienceGainFromGear: 0,
    skipNonEliteEnemyEncountersChanceFromGear: 0,
    igniteCarryToSubsequentEnemiesFromGear: false,
    chillCarryToSubsequentEnemiesFromGear: false,
    preventDeathOncePerStageFromGear: false,
    moreSpeedIfDeathPreventedThisStagePercentFromGear: 0,
    takeChaosDamagePerSecondIfDeathPreventedFromGear: 0,
    pctIncreasedAttributeRequirementsFromGear: 0,
    takeChaosDamageEqualToPctOfAbilityCostOnSpellCastFromGear: 0,
    extraHitOnCritChanceFromGear: 0,
    blockReplacedByDodgeFromGear: false,
    dodgeRolledTwiceAtMaxLifeBetterFromGear: false,
    dodgeRolledTwiceBelowMaxLifeWorseFromGear: false,
    doubleDamageUpgradesToTripleChanceFromGear: 0,
    tripleDamageUpgradesToQuadrupleChanceFromGear: 0,
    cannotEvadeWhileYouHaveEnergyShieldFromGear: false,
    blockPreventsAllDamageChanceFromGear: 0,
    pctIncreasedLifeFromGear: 0,
    pctIncreasedManaFromGear: 165,
    pctIncreasedArmourFromGear: 22.8,
    pctIncreasedEvasionFromGear: 22.8,
    pctIncreasedEnergyShieldFromGear: 88.1,
    increasedMeleeDamageFromGear: 0,
    increasedAttackDamageFromGear: 0,
    increasedDamageFromGear: 0,
    increasedSpellDamageFromGear: 0,
    pctIncreasedAccuracyFromGear: 0,
    pctIncreasedAttackSpeedFromGear: 0,
    doubleDamageChanceFromGear: 0,
    armourIgnoreFromGear: 0,
    pctToAllElementalResFromGear: 61,
    pctChaosResFromGear: 49,
    manaCostReductionFromGear: 0,
    energyShieldLessMultFromGear: 1,
    flatEnergyShieldFromGear: 304,
    weaponEffectiveAps: null,
    weaponBaseCritChance: null,
    blockChanceFromGear: 25,
    flatStrikesPerAttack: 0,
    increasedStrikesPerAttackFromGear: 0,
    strikesIncPctPer10DexFromGear: 0,
    pctIncreasedCriticalHitChanceFromGear: 0,
    increasedElementalDamageFromGear: 0,
    bleedInflictChanceFromGear: 0,
    poisonInflictChanceFromGear: 0,
    elementalAilmentInflictChanceFromGear: 0,
    chillInflictChanceFromGear: 0,
    shockInflictChanceFromGear: 0,
    igniteInflictChanceFromGear: 0,
    dotDamageMoreMultFromGear: 1,
    strikesMoreMultFromGear: 1,
    attackSpeedLessMultFromGear: 0.99,
    accuracyLessMultFromGear: 1,
    lifeOnHitFromGear: 0,
    lifeLeechFromHitDamagePercentFromGear: 0,
    lifeLeechFromPhysicalHitPercentFromGear: 0,
    physicalConvertedToFirePctFromGear: 0,
    physicalConvertedToColdPctFromGear: 0,
    physicalConvertedToLightningPctFromGear: 0,
    lightningPenetrationFromGear: 0,
    hitsCannotBeEvadedFromGear: false,
    cannotDealCriticalStrikesFromGear: false,
    pctFireResFromGear: 0,
    pctColdResFromGear: 0,
    pctLightningResFromGear: 0,
    pctToAllResistancesFromGear: 0,
    dodgeChanceFromGear: 0,
    dodgeChancePer10DexFromGear: 0,
    maxDodgeChanceBonusFromGear: 0,
    pctIncreasedCastSpeedFromGear: 74,
    castSpeedLessMultFromGear: 1,
    castSpeedIncPctPer10DexFromGear: 0,
    increasedCriticalDamageMultiplierFromGear: 0,
    flatCriticalDamageMultiplierBonusFromGear: 0,
    attackBaseCritChanceBonusFromGear: 0,
    spellBaseCritChanceBonusFromGear: 0,
    tripleDamageChanceFromGear: 0,
    blockPowerPctFromGear: 0,
    armourEffectivenessVsChaosFromGear: 0.48,
    increasedLightningDamageFromGear: 0,
    increasedChaosDamageFromGear: 0,
    pctIncreasedDamageOverTimeFromGear: 0,
    pctIncreasedBleedDamageFromGear: 0,
    ailmentDurationBonusFromGear: 0,
    ailmentDurationLessMultFromGear: 1,
    igniteDurationLessMultFromGear: 1,
    pctIncreasedAllAttributesFromGear: 0,
    pctIncreasedStrengthFromGear: 0,
    pctIncreasedDexterityFromGear: 0,
    pctIncreasedIntelligenceFromGear: 39,
    damageTakenLessMultFromGear: 1,
    damageTakenMoreMultFromGear: 1,
    lifeRegenPercentOfMaxLifePerSecondFromGear: 0,
    manaRegenPercentOfMaxManaPerSecondFromGear: 3,
    esRegenPercentOfMaxPerSecondFromGear: 1,
    lifeAsExtraEsPercentFromGear: 0,
    manaAsExtraEsPercentFromGear: 17,
    enemyDamageTakenIncreasedFromGear: 0,
    firePenetrationFromGear: 0,
    coldPenetrationFromGear: 0,
    chaosPenetrationFromGear: 0,
    elementalPenetrationFromGear: 20,
    elementalToChaosConversionPctFromGear: 0,
    physicalToRandomElementPctFromGear: 0,
    lightningToColdConversionPctFromGear: 0,
    gainPhysicalAsExtraLightningPctFromGear: 0,
    evasionMoreMultFromGear: 1,
    cannotInflictElementalAilmentsFromGear: false,
    hitsTakenCannotBeCriticalFromGear: false,
    damageDealtLessMultFromGear: 1,
    lifeMoreMultFromGear: 1,
    manaMoreMultFromGear: 1,
    defencesLessMultFromGear: 1,
    manaCostIncreasePercentFromGear: 0,
    pctIncreasedManaRegenFromGear: 111,
    pctIncreasedLifeRecoveryFromGear: 0,
    doubleDamageChanceFromSpellsFromGear: 0,
    maxBlockChanceBonusFromGear: 0,
    physicalTakenAsChaosPercentFromGear: 0,
    elementalTakenAsChaosPercentFromGear: 0,
    physicalTakenAsFirePercentFromGear: 0,
    physicalTakenAsColdPercentFromGear: 0,
    physicalTakenAsLightningPercentFromGear: 0,
    reducedPhysicalDamageTakenFromGear: 24,
    nonDamagingAilmentEffectIncreasedFromGear: 0,
    chillInflictEffectMultFromGear: 1,
    abilitiesNoCostFromGear: false,
    dealNoDamageExceptCritFromGear: false,
    increasedFireDamageFromGear: 95,
    increasedColdDamageFromGear: 0,
    maxFireResBonusFromGear: 0,
    maxColdResBonusFromGear: 0,
    maxLightningResBonusFromGear: 0,
    maxAllElementalResBonusFromGear: 0,
    maxChaosResBonusFromGear: 0,
    damageTakenToManaFirstPercentFromGear: 0,
    lifeRecoveredOnKillPercentFromGear: 0,
    flatLifeOnKillFromGear: 0,
    manaOnKillFlatFromGear: 0,
    lifeRecoveredOnBlockPercentFromGear: 0,
    flatLifeOnBlockFromGear: 0,
    manaRecoveredOnBlockPercentFromGear: 0,
    esRecoveredOnBlockPercentFromGear: 0,
    flatManaOnBlockFromGear: 0,
    flatEsOnBlockFromGear: 0,
    energyShieldOnHitFromGear: 0,
    rangedDamageIncPctPer10StrFromGear: 0,
    damageIncPctPer10CombinedAttrsFromGear: 0,
    manaCostPaidWithLifeFromGear: false,
    increasedItemRarityFromGear: 85,
    increasedItemQuantityFromGear: 0,
    critIncPctPerItemRarityPctFromGear: 0,
    critMultiPctPerItemQuantityPctFromGear: 0,
    critMultiPctPer20AccuracyFromGear: 0,
    additionalAbilityLevelsAllFromGear: 2,
    additionalAbilityLevelsColdFromGear: 0,
    maxShockEffectBonusFromGear: 0,
    maxChillEffectBonusFromGear: 0,
    increasedShockEffectFromGear: 0,
    shockDurationMoreMultFromGear: 1,
    enemiesDealLessDamageFromGear: 0,
    enemiesHaveMoreSpeedFromGear: 0,
    enemyResistancesEqualToYoursFromGear: false,
    enemiesUnaffectedByChillFromGear: false,
    fixedCritChancePercentFromGear: 0,
    blockChanceMultiplierFromGear: 1,
    cannotEvadeFromGear: false,
    cannotDodgeFromGear: false,
    manaCostPaidWithEnergyShieldFromGear: false,
    noManaFromGear: false,
    manaRegenToEnergyShieldPercentFromGear: 0,
    cannotEvadeWhileAboveHalfLifeFromGear: false,
    cannotRecoverLifeWhileAboveHalfLifeFromGear: false,
    armourHasNoEffectWhileBelowHalfLifeFromGear: false,
    sacrificeCurrentManaPercentPerSecondFromGear: 25,
    poisonYouInflictReflectedToYouFromGear: false,
    elementalAilmentsYouInflictReflectedToYouFromGear: false,
    moreSpeedPerPoisonOnYouPercentFromGear: 0,
    moreSpeedPerShockEffectOnYouPerPctFromGear: 0,
    lifeRegenPercentOfMaxPerSecondWhileIgnitedFromGear: 0,
    unaffectedByChillFromGear: false,
    manaRecoveredOnKillPercentFromGear: 0,
    moreAttackAndCastSpeedPer50CurrentManaPctFromGear: 1,
    moreAccuracyRatingPer0_1sAttackTimePctFromGear: 0,
    poisonDamageTakenLessPercentFromGear: 0,
    flatLifeRegenPerSecondPerCharacterLevelFromGear: 0,
    loseLifePerSecondFromGear: 0,
    takeChaosDamagePerSecondFromGear: 0,
    pctDexIntConvertedToStrFromGear: 0,
    convertEvasionToArmourFromGear: false,
    energyShieldCannotBeReducedBelowMaximumFromGear: false,
    countsAsDualWieldingFromGear: false,
    armourEqualToPercentOfMaxManaFromGear: 40,
    lifeLeechAppliesToEnergyShieldFromGear: false,
    spellHitDamageLeechedAsEnergyShieldPercentFromGear: 0,
    excessLifeLeechRecoveryToEnergyShieldFromGear: false,
    pctIncreasedRecoveryFromAllSourcesFromGear: 0,
  },
  ability: { abilityId: "ability_blazing_radiance", abilityLevel: 20, attunementPct: 100 },
  equipped: {
    Helmet: { itemId: "unique_the_gilden_apex", rolls: [20, 6, 10], enhancement: 40 },
    Chest: { itemId: "unique_mind_bulwark", rolls: [20, 19, 48], enhancement: 10 },
    Belt: { itemId: "unique_circling_thoughts", rolls: [20, 58], enhancement: 9 },
    Gloves: {
      itemId: "equip_gloves",
      enhancement: 10,
      craftedPrefixes: [
        { modifierId: "prefix_additional_level_to_all_abilities", roll1: 2 },
        { modifierId: "prefix_increased_arcana_gain_from_enemies", roll1: 40 },
      ],
      craftedSuffixes: [
        { modifierId: "suffix_intelligence", roll1: 55 },
        { modifierId: "suffix_increased_cast_speed", roll1: 24 },
      ],
    },
    Boots: { itemId: "unique_the_parallax", rolls: [185, 12], enhancement: 10 },
    Weapon: {
      itemId: "equip_sceptre",
      enhancement: 10,
      craftedPrefixes: [
        { modifierId: "prefix_added_cold_damage_to_spells", roll1: 134, roll2: 257 },
        { modifierId: "prefix_increased_fire_damage", roll1: 95 },
      ],
      craftedSuffixes: [
        { modifierId: "suffix_increased_cast_speed", roll1: 50 },
        { modifierId: "suffix_elemental_resistance_penetration", roll1: 20 },
      ],
    },
    "Off-hand": { itemId: "unique_remnant_of_the_ages", rolls: [67, 29, 44, 17], enhancement: 7 },
    "Ring 1": {
      itemId: "equip_amethyst_ring",
      enhancement: 9,
      craftedPrefixes: [
        { modifierId: "prefix_mana", roll1: 119 },
        { modifierId: "prefix_increased_item_rarity", roll1: 35 },
      ],
      craftedSuffixes: [
        { modifierId: "suffix_intelligence", roll1: 49 },
        { modifierId: "suffix_increased_mana_regeneration", roll1: 75 },
      ],
    },
    "Ring 2": {
      itemId: "equip_amethyst_ring",
      enhancement: 3,
      craftedPrefixes: [
        { modifierId: "prefix_mana", roll1: 86 },
        { modifierId: "prefix_evasion_rating", roll1: 215 },
      ],
      craftedSuffixes: [
        { modifierId: "suffix_all_elemental_resistances", roll1: 19 },
        { modifierId: "suffix_increased_mana_regeneration", roll1: 36 },
      ],
    },
    Amulet: { itemId: "unique_soulstone_talisman", rolls: [34, 49, 19, 3], enhancement: 10 },
  },
};

const stats = computeBuildStats(config);

// High-signal outputs for debugging mismatches.
console.log(
  JSON.stringify(
    {
      classBonusesActive: stats.classBonusesActive,
      hitDamage: { min: stats.hitDamageMin, max: stats.hitDamageMax, byType: stats.hitDamageByType },
      cast: { aps: stats.aps, castTime: stats.aps > 0 ? 1 / stats.aps : null },
      manaCostPerCast: stats.manaCostPerAttack,
      shock: {
        elementalAilmentChance: stats.elementalAilmentChance,
        shockBonus: stats.shockInflictChanceBonus,
        nonDamagingAilmentEffectInc: stats.nonDamagingAilmentEffectIncreasedPercent,
        ailmentDurationMult: stats.ailmentDurationMultiplier,
      },
      pen: stats.elementalPenetrationPercent,
      def: {
        armour: stats.armour,
        evasionRating: stats.evasionRating,
        energyShield: stats.maxEnergyShield,
        block: stats.blockChance,
        dodge: stats.dodgeChance,
        manaBeforeLife: stats.damageTakenToManaFirstPercent,
        res: {
          fire: stats.fireRes,
          cold: stats.coldRes,
          lightning: stats.lightningRes,
          chaos: stats.chaosRes,
          maxChaos: stats.maxChaosRes,
        },
        reducedPhysTaken: stats.reducedPhysicalDamageTaken,
      },
      rec: {
        manaRegen: stats.manaRegenPerSecond,
        esRegen: stats.esRegenPerSecond,
      },
      attrs: { life: stats.maxLife, mana: stats.maxMana, str: stats.str, dex: stats.dex, int: stats.int },
      rarity: { itemRarity: stats.increasedItemRarityFromGear, arcana: stats.increasedArcanaGainFromEnemies },
      spellBreakdown: stats.spellDamageComputationBreakdown ?? null,
    },
    null,
    2
  )
);

